# Change these first
owner: TabbyML # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Hugging Face
    url: https://huggingface.co
    method: GET

  - name: GitHub
    url: https://github.com
    method: GET
    
status-website:
  cname: uptime.tabbyml.com
  theme: light
  logoUrl: https://tabbyml.github.io/tabby/img/logo.png
  themeUrl: https://cdn.statically.io/gh/TabbyML/uptime/master/assets/tabby.css
  name: TabbyML Status
  introTitle: Uptime stats for TabbyML
  introMessage: "**Tabby** is the open-source AI coding assistant, powered by TabbyML, Inc."
  navbar:
    - title: Status
      href: /
    - title: Github
      href: https://github.com/tabbyml/tabby
    
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
